name: Approve Command Dispatch

on:
  push:

jobs:
  approve-command-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # pin@v2.4.2

      - name: Get Issue Body
        id: get-issue-body
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: |
          BODY="### Model Name\r\n\r\nmy cool molecule\r\n\r\n### Model Description\r\n\r\nThis is a prediction for a super cool molecule\r\n\r\n### Ersilia ID\r\n\r\neos11aa\r\n\r\n### Publication\r\n\r\nThe following link is just an example:\r\n\r\nwww.example.com\r\n\r\n### Code\r\n\r\n_No response_\r\n\r\n### License\r\n\r\n_No response_"
          echo "::set-output name=body::$BODY"

      - run: echo ${{ steps.get-issue-body.outputs.body }}

      - name: Issue Template Parser
        id: issue-parser
        uses: stefanbuck/github-issue-parser@v3.0.1
        with:
          issue-body: ${{ steps.get-issue-body.outputs.body }}
          template-path: .github/ISSUE_TEMPLATE/model_request.yml

      - run: echo "$ISSUE_CONTEXT"
        env:
          ISSUE_CONTEXT: ${{ steps.issue-parser.outputs.jsonString }}
